name: fizz_live
description: "Fizz Live Video Streaming and Dating App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  zego_uikit_prebuilt_live_streaming: ^3.14.3
  zego_express_engine: any
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
