name: fizz_live
description: Fizz Live Pro Android Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  zego_uikit_prebuilt_live_streaming: ^3.15.6

flutter:
  uses-material-design: true
  
