name: fizz_live
description: "A real-time live video streaming and matchmaking application."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  zego_uikit_prebuilt_live_streaming: ^3.14.3
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
  
